import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:mealsapp/categories.dart';
import 'recipe_model.dart';

import './cg_model.dart';

const DummyCategories = const [
  Model(
    id: 'c1',
    title: 'Italian',
    color: Colors.purple,
  ),
  Model(
    id: 'c2',
    title: 'Quick & Easy',
    color: Colors.red,
  ),
  Model(
    id: 'c3',
    title: 'Hamburgers',
    color: Colors.orange,
  ),
  Model(
    id: 'c4',
    title: 'German',
    color: Colors.amber,
  ),
  Model(
    id: 'c5',
    title: 'Light & Lovely',
    color: Colors.blue,
  ),
  Model(
    id: 'c6',
    title: 'Exotic',
    color: Colors.green,
  ),
  Model(
    id: 'c7',
    title: 'Breakfast',
    color: Colors.lightBlue,
  ),
  Model(
    id: 'c8',
    title: 'Asian',
    color: Colors.lightGreen,
  ),
  Model(
    id: 'c9',
    title: 'French',
    color: Colors.pink,
  ),
  Model(
    id: 'c10',
    title: 'Summer',
    color: Colors.teal,
  ),
];

const DummyRecipes = const [
  Recipes(
   title: 'Spaghetti',
   id: 'm1',
   belongsToCg: ['c1', 'c2'],
   imageUrl: 'https://www.inspiredtaste.net/wp-content/uploads/2019/03/Spaghetti-with-Meat-Sauce-Recipe-1-1200.jpg',
   ingredients: ['blah', 'bleh', 'bloh'],
   steps: ['Cut the blah', 'Mix the bleh', 'Fry the bloh'],
   duration: 20,
   complexity: Complexity.Simple,
   cost: Cost.Cheap,
   isGlutenFree: false,
   isVegan: true,
   isVegetarian: true,
   isLactoseFree: false,
  ),

  Recipes(
    title: 'Toast Hawaii',
    id: 'm2',
    belongsToCg: ['c2'],
    imageUrl: 'https://www.simplyrecipes.com/wp-content/uploads/2010/01/cinnamon-toast-horiz-a-1800-768x512.jpg',
    ingredients: ['blah', 'bleh', 'bloh'],
    steps: ['Cut the blah', 'Mix the bleh', 'Fry the bloh'],
    duration: 10,
    complexity: Complexity.Simple,
    cost: Cost.Cheap,
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: false,
  ),

  Recipes(
    title: 'Classic hamburger',
    id: 'm3',
    belongsToCg: ['c3'],
    imageUrl: 'https://barbecuebible.com/wp-content/uploads/2013/05/featured-great-american-hamburger.jpg',
    ingredients: ['blah', 'bleh', 'bloh'],
    steps: ['Cut the blah', 'Mix the bleh', 'Fry the bloh'],
    duration: 20,
    complexity: Complexity.Challenging,
    cost: Cost.Moderate,
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),

  Recipes(
    title: 'Wiener Schnitzel',
    id: 'm4',
    belongsToCg: ['c4'],
    imageUrl: 'https://www.daringgourmet.com/wp-content/uploads/2014/03/Schnitzel-5.jpg',
    ingredients: ['blah', 'bleh', 'bloh'],
    steps: ['Cut the blah', 'Mix the bleh', 'Fry the bloh'],
    duration: 10,
    complexity: Complexity.Hard,
    cost: Cost.Expensive,
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: false,
    isLactoseFree: false,
  ),

  Recipes(
    title: 'Salad with Smoked Salmon',
    id: 'm5',
    belongsToCg: ['c2', 'c5', 'c10'],
    imageUrl: 'https://www.dinneratthezoo.com/wp-content/uploads/2019/02/salmon-salad-4.jpg',
    ingredients: ['blah', 'bleh', 'bloh'],
    steps: ['Cut the blah', 'Mix the bleh', 'Fry the bloh'],
    duration: 20,
    complexity: Complexity.Hard,
    cost: Cost.Moderate,
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),

  Recipes(
    title: 'Delicioius Orange Mousse',
    id: 'm6',
    belongsToCg: ['c6', 'c10'],
    imageUrl: 'https://t2.uc.ltmcdn.com/en/images/1/2/1/img_making_orange_mousse_121_600_square.jpg',
    ingredients: ['blah', 'bleh', 'bloh'],
    steps: ['Cut the blah', 'Mix the bleh', 'Fry the bloh'],
    duration: 125,
    complexity: Complexity.Challenging,
    cost: Cost.Expensive,
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: false,
  ),

  Recipes(
    title: 'Pancakes',
    id: 'm7',
    belongsToCg: ['c7'],
    imageUrl: 'https://www.inspiredtaste.net/wp-content/uploads/2016/07/Pancake-Recipe-1-1200.jpg',
    ingredients: ['blah', 'bleh', 'bloh'],
    steps: ['Cut the blah', 'Mix the bleh', 'Fry the bloh'],
    duration: 28,
    complexity: Complexity.Challenging,
    cost: Cost.Moderate,
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),

  Recipes(
    title: 'Creamy Indian Chicken Curry',
    id: 'm8',
    belongsToCg: ['c8'],
    imageUrl: 'https://hips.hearstapps.com/del.h-cdn.co/assets/17/31/1501791674-delish-chicken-curry-horizontal.jpg?crop=1.00xw:0.750xh;0,0.159xh&resize=1200:*',
    ingredients: ['blah', 'bleh', 'bloh'],
    steps: ['Cut the blah', 'Mix the bleh', 'Fry the bloh'],
    duration: 10,
    complexity: Complexity.Simple,
    cost: Cost.Cheap,
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Recipes(
    title: 'Chocolate Souffle',
    id: 'm9',
    belongsToCg: ['c9'],
    imageUrl: 'https://imagesvc.meredithcorp.io/v3/mm/image?q=85&c=sc&poi=face&w=750&h=393&url=https%3A%2F%2Fassets.marthastewart.com%2Fstyles%2Fwmax-750%2Fd27%2Fchocolate-souffle-med107742%2Fchocolate-souffle-med107742_horiz.jpg%3Fitok%3Dh6VrTFqc',
    ingredients: ['blah', 'bleh', 'bloh'],
    steps: ['Cut the blah', 'Mix the bleh', 'Fry the bloh'],
    duration: 35,
    complexity: Complexity.Challenging,
    cost: Cost.Moderate,
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),

  Recipes(
    title: 'Asparagus salad with cherry tomatoes',
    id: 'm10',
    belongsToCg: ['c2', 'c5', 'c10'],
    imageUrl: 'https://www.cookingclassy.com/wp-content/uploads/2016/03/asparagus_salad18..jpg',
    ingredients: ['blah', 'bleh', 'bloh'],
    steps: ['Cut the blah', 'Mix the bleh', 'Fry the bloh'],
    duration: 52,
    complexity: Complexity.Simple,
    cost: Cost.Moderate,
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  
];